
allowed_headings = [
    "Informed Consent Type",
    "Duration",
    "Based On Date",
    "Program",
    "Disease",
    "Drug Study",
    "Long Term Sample Storage",
    "Future Research for Samples",
    "Future Research for Samples Allowable Use",
    "Genetic or Genomic Studies Explanation",
    "Genetic or Genomic Research Risk",
    "Specimen Storage Duration Main Study",
    "Specimen Storage Duration Future Research",
    "Specimen Storage Location Main Study",
    "Specimen Storage Location Future Research",
    "Specimen Anonymization",
    "Specimen Sharing Main Study",
    "Specimen Sharing Future Research",
    "Data Usage",
    "Data Storage Duration",
    "Data Anonymization",
    "Data Sharing Main Study",
    "Sharing of Study Results with Patient - Main Study",
    "Sharing of Study Results with Patient - Future Research",
    "At Consent Withdrawal - Samples",
    "At Consent Withdrawal - Data",
    "Copy of ICF"
]
